### PR TITLE
[WIP] Update parameter parsing and fix dry_run

### LINKED ISSUE #41: pick reasonable env var names

### PR DESCRIPTION
**Pull request by fsck**
Trying to fix #41 as discussed previously. Feel feel to push to this branch @Trolldemorted

### CODE REVIEW

**Comment by Trolldemorted** [comment]
What has gotta be done?

Do we need a dry run? If it means 'not deploying', you can leave the servers empty, if it means 'not storing' it doesn't make much sense.

**Comment by fsck** [comment]
I would interpret it as do everything but deploy. This would also makes sense for our internal testing (I think), as we can do everything up until actually connecting over ssh, without a valid remote end.

What needs to be done: Testing it a bit more and fixing the docker container because looking at it again this morning I probably messed up the parameters in the entry point.

**Comment by Trolldemorted** [comment]
I am not certain that a parameter for that does make sense. If you do not want to deploy, you can always add no servers or just not hit the deploy button.

**Comment by fsck** [comment]
Because we might actually want to preconfigure the targets but not actually run them in a preparation to an event or, more importantly, we want to actually exercise the code paths in tests without having an live remote available. We need to think about a sensible testing strategy anyway.

**Pull request closed without merging**
