### PR TITLE
added travis ci, fixes #7

### LINKED ISSUE #7: continuous integration

### PR DESCRIPTION
**Pull request by bitwave**

### CODE REVIEW

**Review by fsck — CHANGES_REQUESTED** [review]
As this project depends on nightly we need to change the Travis config to only build on nightly and remove the allow_failures. Otherwise very good, thank you.

**Comment by bitwave** [comment]
added changes

**Comment by Trolldemorted** [comment]
This still is has conflicts with the current master. Do we want our badges above or below the headline btw?

**Comment by fsck** [comment]
> This still is has conflicts with the current master. Do we want our badges above or below the headline btw?

I am fine either way. What is the industry best practice?

**Comment by Trolldemorted** [comment]
/shrug [pcap does everything in one line and I kinda like it](https://github.com/ebfull/pcap), [Signal-Windows does it above the heading](https://github.com/signal-csharp/Signal-Windows)

**Review by fsck — APPROVED** [review]

**Pull request merged**
